// <auto-generated />
using System;
using BlocoNotas.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlocoNotas.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250604094226_InitialAzureMigration")]
    partial class InitialAzureMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlocoNotas.Models.Note", b =>
                {
                    b.Property<int>("NoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NoteId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("UserFK")
                        .HasColumnType("int");

                    b.HasKey("NoteId");

                    b.HasIndex("UserFK");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("BlocoNotas.Models.NoteShare", b =>
                {
                    b.Property<int>("NoteShareId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NoteShareId"));

                    b.Property<bool>("CanEdit")
                        .HasColumnType("bit");

                    b.Property<int>("NoteShareFK")
                        .HasColumnType("int");

                    b.Property<DateTime>("SharedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("UserShareFK")
                        .HasColumnType("int");

                    b.HasKey("NoteShareId");

                    b.HasIndex("NoteShareFK");

                    b.HasIndex("UserShareFK");

                    b.ToTable("NoteShares");
                });

            modelBuilder.Entity("BlocoNotas.Models.NoteTag", b =>
                {
                    b.Property<int>("NoteTagFK")
                        .HasColumnType("int");

                    b.Property<int>("TagFK")
                        .HasColumnType("int");

                    b.HasKey("NoteTagFK", "TagFK");

                    b.HasIndex("TagFK");

                    b.ToTable("NoteTags");
                });

            modelBuilder.Entity("BlocoNotas.Models.Tag", b =>
                {
                    b.Property<int>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TagId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TagId");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("BlocoNotas.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BlocoNotas.Models.Note", b =>
                {
                    b.HasOne("BlocoNotas.Models.User", "User")
                        .WithMany("Notes")
                        .HasForeignKey("UserFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BlocoNotas.Models.NoteShare", b =>
                {
                    b.HasOne("BlocoNotas.Models.Note", "Note")
                        .WithMany("SharedWith")
                        .HasForeignKey("NoteShareFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlocoNotas.Models.User", "SharedWithUser")
                        .WithMany("SharedWithMe")
                        .HasForeignKey("UserShareFK")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Note");

                    b.Navigation("SharedWithUser");
                });

            modelBuilder.Entity("BlocoNotas.Models.NoteTag", b =>
                {
                    b.HasOne("BlocoNotas.Models.Note", "Note")
                        .WithMany("NoteTags")
                        .HasForeignKey("NoteTagFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlocoNotas.Models.Tag", "Tag")
                        .WithMany("NoteTags")
                        .HasForeignKey("TagFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Note");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("BlocoNotas.Models.Note", b =>
                {
                    b.Navigation("NoteTags");

                    b.Navigation("SharedWith");
                });

            modelBuilder.Entity("BlocoNotas.Models.Tag", b =>
                {
                    b.Navigation("NoteTags");
                });

            modelBuilder.Entity("BlocoNotas.Models.User", b =>
                {
                    b.Navigation("Notes");

                    b.Navigation("SharedWithMe");
                });
#pragma warning restore 612, 618
        }
    }
}
